# Generated by Django 5.1.1 on 2024-09-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('B', 'Buy'), ('R', 'Rent')], max_length=1),
        ),
    ]
